// Mocks generated by Mockito 5.3.2 from annotations
// in weather_stations/data/models/current_weather_model.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_stations/data/models/current_weather_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrentWeatherModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentWeatherModel extends _i1.Mock
    implements _i2.CurrentWeatherModel {
  @override
  set coord(_i2.Coord? _coord) => super.noSuchMethod(
        Invocation.setter(
          #coord,
          _coord,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set weather(List<_i2.CurrentWeather?>? _weather) => super.noSuchMethod(
        Invocation.setter(
          #weather,
          _weather,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set base(String? _base) => super.noSuchMethod(
        Invocation.setter(
          #base,
          _base,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set main(_i2.Main? _main) => super.noSuchMethod(
        Invocation.setter(
          #main,
          _main,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set visibility(int? _visibility) => super.noSuchMethod(
        Invocation.setter(
          #visibility,
          _visibility,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set wind(_i2.Wind? _wind) => super.noSuchMethod(
        Invocation.setter(
          #wind,
          _wind,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set clouds(_i2.Clouds? _clouds) => super.noSuchMethod(
        Invocation.setter(
          #clouds,
          _clouds,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set dt(int? _dt) => super.noSuchMethod(
        Invocation.setter(
          #dt,
          _dt,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set sys(_i2.Sys? _sys) => super.noSuchMethod(
        Invocation.setter(
          #sys,
          _sys,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set timezone(int? _timezone) => super.noSuchMethod(
        Invocation.setter(
          #timezone,
          _timezone,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set cod(int? _cod) => super.noSuchMethod(
        Invocation.setter(
          #cod,
          _cod,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
